name: integration-test

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Aspire Workload
      run: dotnet workload install aspire

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'AspireTesting/appsettings.json'
      env:
        ConnectionStrings.AppDatabase: ${{ secrets.CONNECTIONSTRINGS_APPDATABASE }}

    - name: Install Podman
      uses: gacts/install-podman@v1

    - name: Tests
      run: dotnet test AspireTesting.sln --verbosity normal --configuration Release