name: unit-test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Aspire
      run: dotnet workload install aspire

    - name: Restore dependencies
      run: dotnet restore

    - name: Unit Tests
      run: dotnet test AspireTesting.sln --filter Category!=Integration --verbosity normal --configuration Release